DROP TABLE WRK_EXCHANGE_SALES;
  CREATE TABLE WRK_EXCHANGE_SALES
    TABLESPACE "USERS" 
    FOR EXCHANGE WITH TABLE FCT_SALES;
   
ALTER TABLE WRK_EXCHANGE_SALES MODIFY
    PARTITION BY HASH (CUSTOMER_SURR_ID) ;

CREATE OR REPLACE PUBLIC SYNONYM WRK_EXCHANGE_SALES FOR BL_CL.WRK_EXCHANGE_SALES;

