
ALTER SESSION SET "_ORACLE_SCRIPT" = true;

CREATE USER BL_3NF IDENTIFIED BY BL_3NF		
 DEFAULT TABLESPACE users
 TEMPORARY TABLESPACE temp
 PROFILE default;

GRANT connect, resource TO BL_3NF;
GRANT UNLIMITED TABLESPACE TO BL_3NF;
