ALTER SESSION SET "_ORACLE_SCRIPT" = true;

CREATE USER SA_INSTORE IDENTIFIED BY SA_INSTORE 		
 DEFAULT TABLESPACE users
 TEMPORARY TABLESPACE temp
 PROFILE default;

GRANT connect, resource TO SA_INSTORE;
GRANT UNLIMITED TABLESPACE TO SA_INSTORE;
