ALTER SESSION SET "_ORACLE_SCRIPT" = true;

CREATE USER SA_ONLINE IDENTIFIED BY SA_ONLINE 		
 DEFAULT TABLESPACE users
 TEMPORARY TABLESPACE temp
 PROFILE default;

GRANT connect, resource TO SA_ONLINE;
GRANT UNLIMITED TABLESPACE TO SA_ONLINE;
